### ISSUE TITLE
What rails verion is Webiva built on?

### ISSUE THREAD

**Issue by topstarnetwork** [cykod/Webiva#10]
Hello,
What rails verion is Webiva built on?
Is it latest rails 4 version?
If not are you planing to upgrade to latest rails version?
Thanks.

**Comment by cykod** [comment]
Webiva isn't being developed anymore (hasn't been for over three years) - it's Rails 2, and will not be upgraded.

**Comment by topstarnetwork** [comment]
This is very sad, I loved the way it was built like joomla or wordpress where you can create addons and isntall them.
Would there be any such webiva ruby on rails alternative you could advise me?
A ruby on rails that has the same features and architecture?
Regards, Heather
